#!/usr/bin/env bash
#script than lanch nginx on port 80
apt-get -y update
apt-get install -y nginx
sudo sed -i '0,/listen.*/s/listen.*/listen 80 default_server;/' /etc/nginx/sites-enabled/default
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i "\t\t\t/server_name/a \\\nrewrite ^/(.*) https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
sudo service nginx restart
