#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
COUNTER=0
while ((COUNTER<=10))
do
	if ((COUNTER==9))
	then 
		echo "Hi"
	else 
		echo "Holberton School"
	fi 
	((++COUNTER))
done
