#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
HOUR=0
while ((HOUR<=12))
do
	echo "Hour: "$HOUR
	MINUTES=1
	while ((MINUTES<=59))
	do
		echo $MINUTES
		((++MINUTES))
	done	
		((++HOUR))
done
