#!/usr/bin/env bash
#Write a Bash that print the files inside the current folder since of delitator "."
FILE=$PWD/holbertonschool

if test "$FILE";
then
	echo "holbertonschool file exists"
	if test -z "$FILE"
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if test -f "$FILE"
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
