#!/usr/bin/env bash
#File to change the value of the ip in the localhost
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i 8.8.8.8 facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
